<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class BaiHocSeeder extends Seeder
{
    /**
     * Bài học đa dạng — gán xen kẽ hai giáo viên seed.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Nguyên Âm Đơn',
                'mo_ta' => 'Luyện phát âm 11 nguyên âm cơ bản: a, ă, â, e, ê, i, o, ô, ơ, u, ư qua từ vựng thực tế',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 2,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Phụ Âm Môi (b, m, p, ph)',
                'mo_ta' => 'Luyện phụ âm được tạo bằng hai môi và môi-răng — nhóm dễ quan sát nhất cho trẻ',
                'cap_do' => 'basic',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 3,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Phụ Âm Lưỡi (t, th, n, l, d)',
                'mo_ta' => 'Luyện phụ âm đầu lưỡi chạm chân răng và lợi trên',
                'cap_do' => 'basic',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 4,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Phụ Âm Khó (tr, ch, r, s, x)',
                'mo_ta' => 'Luyện nhóm phụ âm quặt lưỡi và xát — nhóm trẻ hay phát âm sai nhiều nhất',
                'cap_do' => 'intermediate',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 5,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Phụ Âm Họng & Gốc Lưỡi',
                'mo_ta' => 'Luyện phụ âm c/k, g, kh, h, ng — âm phát từ sâu trong miệng và cổ họng',
                'cap_do' => 'intermediate',
                'thu_tu' => 5,
                'trang_thai' => 0,
            ],
            [
                'id' => 6,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Sáu Thanh Điệu',
                'mo_ta' => 'Nhận diện và phát âm đúng 6 thanh điệu tiếng Việt qua từ vựng có nghĩa',
                'cap_do' => 'intermediate',
                'thu_tu' => 6,
                'trang_thai' => 0,
            ],
            [
                'id' => 7,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Vần Thường Gặp (-an, -at, -am)',
                'mo_ta' => 'Luyện kết hợp âm cuối mũi và tắc phổ biến nhất trong tiếng Việt',
                'cap_do' => 'intermediate',
                'thu_tu' => 7,
                'trang_thai' => 0,
            ],
            [
                'id' => 8,
                'danh_muc_id' => 1,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Vần Nâng Cao (-ong, -oc, -ang)',
                'mo_ta' => 'Luyện vần với âm cuối gốc lưỡi — âm trẻ rối loạn ngôn ngữ hay nuốt mất',
                'cap_do' => 'advanced',
                'thu_tu' => 8,
                'trang_thai' => 0,
            ],
            [
                'id' => 9,
                'danh_muc_id' => 2,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Các Thành Viên Gia Đình',
                'mo_ta' => 'Từ vựng về những người thân trong gia đình gần gũi với trẻ',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 10,
                'danh_muc_id' => 2,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Khuôn Mặt',
                'mo_ta' => 'Từ vựng về các bộ phận trên khuôn mặt người',
                'cap_do' => 'basic',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 11,
                'danh_muc_id' => 2,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Cơ Thể Phần Trên',
                'mo_ta' => 'Từ vựng về đầu, cổ, vai, tay và các bộ phận phía trên cơ thể',
                'cap_do' => 'basic',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 12,
                'danh_muc_id' => 2,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Cơ Thể Phần Dưới',
                'mo_ta' => 'Từ vựng về chân, gối, bàn chân và các bộ phận phía dưới cơ thể',
                'cap_do' => 'intermediate',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 13,
                'danh_muc_id' => 2,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Cảm Xúc & Trạng Thái',
                'mo_ta' => 'Từ vựng giúp trẻ biểu đạt cảm xúc và trạng thái cơ thể bằng lời nói',
                'cap_do' => 'intermediate',
                'thu_tu' => 5,
                'trang_thai' => 0,
            ],
            [
                'id' => 14,
                'danh_muc_id' => 3,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Trái Cây',
                'mo_ta' => 'Từ vựng về các loại trái cây phổ biến ở Việt Nam',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 15,
                'danh_muc_id' => 3,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Rau Củ',
                'mo_ta' => 'Từ vựng về các loại rau, củ quen thuộc trong bữa ăn hằng ngày',
                'cap_do' => 'basic',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 16,
                'danh_muc_id' => 3,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Món Ăn Hằng Ngày',
                'mo_ta' => 'Từ vựng về các món ăn truyền thống Việt Nam trẻ thường gặp',
                'cap_do' => 'intermediate',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 17,
                'danh_muc_id' => 3,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Đồ Uống',
                'mo_ta' => 'Từ vựng về các loại đồ uống trẻ hay dùng',
                'cap_do' => 'basic',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 18,
                'danh_muc_id' => 3,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Đồ Dùng Bữa Ăn',
                'mo_ta' => 'Từ vựng về dụng cụ ăn uống trong gia đình',
                'cap_do' => 'intermediate',
                'thu_tu' => 5,
                'trang_thai' => 0,
            ],
            [
                'id' => 19,
                'danh_muc_id' => 4,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Vật Nuôi Trong Nhà',
                'mo_ta' => 'Từ vựng về các con vật nuôi gần gũi với trẻ',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 20,
                'danh_muc_id' => 4,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Động Vật Hoang Dã',
                'mo_ta' => 'Từ vựng về các loài động vật sống trong tự nhiên và sở thú',
                'cap_do' => 'intermediate',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 21,
                'danh_muc_id' => 4,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Sinh Vật Biển',
                'mo_ta' => 'Từ vựng về các loài sống dưới nước và đại dương',
                'cap_do' => 'intermediate',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 22,
                'danh_muc_id' => 4,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Côn Trùng & Chim',
                'mo_ta' => 'Từ vựng về các loài côn trùng và chim bay',
                'cap_do' => 'intermediate',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 23,
                'danh_muc_id' => 4,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Tiếng Kêu Động Vật',
                'mo_ta' => 'Luyện phát âm qua mô phỏng tiếng kêu của các con vật — kích thích trẻ tự nhiên bắt chước âm',
                'cap_do' => 'basic',
                'thu_tu' => 5,
                'trang_thai' => 0,
            ],
            [
                'id' => 24,
                'danh_muc_id' => 5,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Các Loài Hoa',
                'mo_ta' => 'Từ vựng về hoa quen thuộc trong cuộc sống và văn hóa Việt Nam',
                'cap_do' => 'intermediate',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 25,
                'danh_muc_id' => 5,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Cây Cối',
                'mo_ta' => 'Từ vựng về các loại cây phổ biến trẻ nhìn thấy hằng ngày',
                'cap_do' => 'intermediate',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 26,
                'danh_muc_id' => 5,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Thời Tiết & Hiện Tượng Thiên Nhiên',
                'mo_ta' => 'Từ vựng về các hiện tượng thời tiết và thiên nhiên',
                'cap_do' => 'intermediate',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 27,
                'danh_muc_id' => 5,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Địa Hình',
                'mo_ta' => 'Từ vựng về các dạng địa hình tự nhiên xung quanh',
                'cap_do' => 'advanced',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 28,
                'danh_muc_id' => 6,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Đồ Dùng Học Tập',
                'mo_ta' => 'Từ vựng về các dụng cụ học tập trẻ dùng hằng ngày',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 29,
                'danh_muc_id' => 6,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Màu Sắc',
                'mo_ta' => 'Từ vựng về màu sắc cơ bản và nâng cao',
                'cap_do' => 'basic',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 30,
                'danh_muc_id' => 6,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Hình Dạng & Kích Thước',
                'mo_ta' => 'Từ vựng về hình học đơn giản và khái niệm kích thước',
                'cap_do' => 'basic',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 31,
                'danh_muc_id' => 6,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Con Số 1–10',
                'mo_ta' => 'Luyện phát âm số đếm từ một đến mười',
                'cap_do' => 'basic',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 32,
                'danh_muc_id' => 6,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Hoạt Động Ở Trường',
                'mo_ta' => 'Từ vựng về các hành động và hoạt động sinh hoạt tại trường',
                'cap_do' => 'intermediate',
                'thu_tu' => 5,
                'trang_thai' => 0,
            ],
            [
                'id' => 33,
                'danh_muc_id' => 7,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Phương Tiện Giao Thông',
                'mo_ta' => 'Từ vựng về các phương tiện di chuyển trẻ thường thấy',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 34,
                'danh_muc_id' => 7,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Nghề Nghiệp',
                'mo_ta' => 'Từ vựng về các nghề nghiệp phổ biến trong xã hội',
                'cap_do' => 'intermediate',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 35,
                'danh_muc_id' => 7,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Nơi Chốn Quen Thuộc',
                'mo_ta' => 'Từ vựng về các địa điểm công cộng và sinh hoạt',
                'cap_do' => 'intermediate',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
            [
                'id' => 36,
                'danh_muc_id' => 7,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Thời Gian',
                'mo_ta' => 'Từ vựng về buổi trong ngày, ngày, tuần, tháng, năm',
                'cap_do' => 'intermediate',
                'thu_tu' => 4,
                'trang_thai' => 0,
            ],
            [
                'id' => 37,
                'danh_muc_id' => 8,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Lời Chào Hỏi',
                'mo_ta' => 'Các từ và cụm từ chào hỏi cơ bản trong giao tiếp hằng ngày',
                'cap_do' => 'basic',
                'thu_tu' => 1,
                'trang_thai' => 0,
            ],
            [
                'id' => 38,
                'danh_muc_id' => 8,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Diễn Đạt Nhu Cầu',
                'mo_ta' => 'Các cụm từ giúp trẻ nói lên nhu cầu và mong muốn của bản thân',
                'cap_do' => 'basic',
                'thu_tu' => 2,
                'trang_thai' => 0,
            ],
            [
                'id' => 39,
                'danh_muc_id' => 8,
                'nguoi_tao_id' => 1,
                'tieu_de' => 'Câu Hỏi Đơn Giản',
                'mo_ta' => 'Các từ để hỏi cơ bản giúp trẻ tương tác và khám phá thế giới',
                'cap_do' => 'intermediate',
                'thu_tu' => 3,
                'trang_thai' => 0,
            ],
        ];

        foreach ($data as &$item) {
            $item['created_at'] = Carbon::now();
            $item['updated_at'] = Carbon::now();
        }

        DB::table('bai_hocs')->insert($data);
    }
}
