<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class NguoiDungSeeder extends Seeder
{
    /** Mật khẩu demo thống nhất cho môi trường phát triển */
    private const MAT_KHAU_DEMO = '123456';

    /**
     * Tài khoản mẫu: admin, giáo viên, học viên — email unique, SĐT đúng 10 số.
     */
    public function run(): void
    {
        $adminRole = DB::table('vai_tros')->where('ten_vai_tro', 'admin')->first()->id;
        $gvRole = DB::table('vai_tros')->where('ten_vai_tro', 'giao_vien')->first()->id;
        $hvRole = DB::table('vai_tros')->where('ten_vai_tro', 'nguoi_dung')->first()->id;

        $matKhauMacDinh = Hash::make('123456');

        $users = [
            // Quản trị
            [
                'ho_ten' => 'Quản trị viên EchoKids',
                'email' => 'admin@echokids.edu.vn',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0123456789',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=12',
                'vai_tro_id' => $adminRole,
                'trang_thai' => 0,
            ],
            // Giáo viên
            [
                'ho_ten' => 'Cô Nguyễn Mai Phương',
                'email' => 'maiphuong.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0987654321',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=32',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],

            [
                'ho_ten' => 'Thầy Nguyễn Văn Hùng',
                'email' => 'nguyenvanhung.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345678',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=11',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Cô Trần Thị Lan',
                'email' => 'tranthilan.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345679',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=12',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Thầy Lê Minh Tuấn',
                'email' => 'leminhtuan.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345680',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=13',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Cô Phạm Thị Hạnh',
                'email' => 'phamthihanh.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345681',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=14',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Thầy Đỗ Văn Nam',
                'email' => 'dovannam.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345682',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=15',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Cô Hoàng Thị Thu',
                'email' => 'hoangthithu.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345683',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=16',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Thầy Vũ Anh Đức',
                'email' => 'vuanhduc.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345684',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=17',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Cô Bùi Thị Ngọc',
                'email' => 'buithingoc.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345685',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=18',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Thầy Phan Quốc Bảo',
                'email' => 'phanquocbao.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345686',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=19',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Cô Nguyễn Thị Ánh',
                'email' => 'nguyenthanh.gv@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345687',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=20',
                'vai_tro_id' => $gvRole,
                'trang_thai' => 0,
            ],

            [
                'ho_ten' => 'Bé Gia Bảo Nguyễn',
                'email' => 'giabao.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt'   => '0912345678',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=52',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [

                'ho_ten' => 'Học viên Nhí Minh Khang',
                'email' => 'minhkhang.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000001',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=53',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Quốc Anh',
                'email' => 'quocanh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000002',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=54',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Gia Huy',
                'email' => 'giahuy.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000003',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=55',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Tuấn Kiệt',
                'email' => 'tuankiet.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000004',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=56',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Bảo Nam',
                'email' => 'baonam.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000005',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=57',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Hoàng Long',
                'email' => 'hoanglong.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000006',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=58',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Đức Anh',
                'email' => 'ducanh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000007',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=59',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Thành Đạt',
                'email' => 'thanhdat.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000008',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=60',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Quang Huy',
                'email' => 'quanghuy.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000009',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=61',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Nhật Minh',
                'email' => 'nhatminh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000010',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=62',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],

            [
                'ho_ten' => 'Học viên Nhí Khánh An',
                'email' => 'khanhan.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000011',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=63',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Bảo Khánh',
                'email' => 'baokhanh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000012',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=64',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Minh Quân',
                'email' => 'minhquan.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000013',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=65',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Quốc Bảo',
                'email' => 'quocbao.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000014',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=66',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Tuấn Anh',
                'email' => 'tuananh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000015',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=67',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Hoàng Anh',
                'email' => 'hoanganh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000016',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=68',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Gia Minh',
                'email' => 'giaminh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000017',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=69',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Bảo An',
                'email' => 'baoan.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000018',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=70',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Đức Minh',
                'email' => 'ducminh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000019',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=71',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Quang Minh',
                'email' => 'quangminh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000020',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=72',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],

            [
                'ho_ten' => 'Học viên Nhí Hải Đăng',
                'email' => 'haidang.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000021',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=73',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Thanh Tùng',
                'email' => 'thanhtung.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000022',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=74',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Trung Kiên',
                'email' => 'trungkien.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000023',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=75',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Anh Tuấn',
                'email' => 'anhtuan.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000024',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=76',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Minh Hiếu',
                'email' => 'minhhieu.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000025',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=77',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Đức Tài',
                'email' => 'ductai.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000026',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=78',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Hoàng Phúc',
                'email' => 'hoangphuc.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000027',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=79',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Gia Khánh',
                'email' => 'giakhanh.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000028',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=80',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Bảo Long',
                'email' => 'baolong.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000029',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=81',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],
            [
                'ho_ten' => 'Học viên Nhí Minh Phúc',
                'email' => 'minhphuc.student@gmail.com',
                'mat_khau' => $matKhauMacDinh,
                'sdt' => '0900000030',
                'anh_dai_dien' => 'https://i.pravatar.cc/300?img=82',
                'vai_tro_id' => $hvRole,
                'trang_thai' => 0,
            ],

        ];

        foreach ($users as $user) {
            DB::table('nguoi_dungs')->updateOrInsert(['email' => $user['email']], $user);
        }
    }
}
